// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GGameShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240121123741_newDb")]
    partial class newDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DevStudio")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("GameCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PricePS")
                        .HasColumnType("float");

                    b.Property<double>("PriceSteam")
                        .HasColumnType("float");

                    b.Property<double>("PriceXbox")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameCategoryId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "After wiping out the gods of Mount Olympus, Kratos moves on to the frigid lands of Scandinavia, where he and his son must embark on an odyssey across a dangerous world of gods and monsters.",
                            DevStudio = "Sony Interactive Entertainment",
                            GameCategoryId = 3,
                            ImageUrl = "C:\\Users\\czare\\source\\repos\\GameShop\\GameShop\\wwwroot\\images\\game\\God_of_War_4_cover.jpg",
                            PricePS = 300.0,
                            PriceSteam = 250.0,
                            PriceXbox = 350.0,
                            Title = "God of War"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Baldur's Gate 3 is a story-rich, party-based RPG set in the universe of Dungeons & Dragons, where your choices shape a tale of fellowship and betrayal, survival and sacrifice, and the lure of absolute power.",
                            DevStudio = "Larian Studios",
                            GameCategoryId = 3,
                            ImageUrl = "C:\\Users\\czare\\source\\repos\\GameShop\\GameShop\\wwwroot\\images\\game\\Baldur's_Gate_3_cover_art.jpg",
                            PricePS = 300.0,
                            PriceSteam = 250.0,
                            PriceXbox = 400.0,
                            Title = "Baldurs Gate 3"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The Witcher 3: Wild Hunt is an action role-playing game with a third-person perspective. Players control Geralt of Rivia, a monster slayer known as a Witcher. Geralt walks, runs, rolls and dodges, and (for the first time in the series) jumps, climbs and swims.",
                            DevStudio = "CDPR",
                            GameCategoryId = 3,
                            ImageUrl = "C:\\Users\\czare\\source\\repos\\GameShop\\GameShop\\wwwroot\\images\\game\\Witcher_3_cover_art.jpg",
                            PricePS = 200.0,
                            PriceSteam = 150.0,
                            PriceXbox = 250.0,
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The cataclysmic conclusion to the Total War: WARHAMMER trilogy is here. Rally your forces and step into the Realm of Chaos, a dimension of mind-bending horror where the very fate of the world will be decided. Will you conquer your Daemons… or command them?",
                            DevStudio = "Creative Assembly",
                            GameCategoryId = 2,
                            ImageUrl = "C:\\Users\\czare\\source\\repos\\GameShop\\GameShop\\wwwroot\\images\\game\\Total_War_Warhammer_3_cover_art.jpg",
                            PricePS = 350.0,
                            PriceSteam = 300.0,
                            PriceXbox = 310.0,
                            Title = "Total War Warhammer 3"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Civilization VI is a turn-based strategy video game in which one or more players compete alongside computer-controlled AI opponents to grow their individual civilization from a small tribe to control the entire planet across several periods of development.",
                            DevStudio = "Firaxis Games",
                            GameCategoryId = 2,
                            ImageUrl = "C:\\Users\\czare\\source\\repos\\GameShop\\GameShop\\wwwroot\\images\\game\\Civilization_VI_cover_art.jpg",
                            PricePS = 150.0,
                            PriceSteam = 100.0,
                            PriceXbox = 200.0,
                            Title = "Civilization VI"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Crusader Kings III is a grand strategy role-playing video game set in the Middle Ages, developed by Paradox Development Studio and published by Paradox Interactive as a sequel to Crusader Kings and Crusader Kings II.",
                            DevStudio = "Paradox Development Studio",
                            GameCategoryId = 2,
                            ImageUrl = "C:\\Users\\czare\\source\\repos\\GameShop\\GameShop\\wwwroot\\images\\game\\Crusader_Kings_III.jpg",
                            PricePS = 199.0,
                            PriceSteam = 200.0,
                            PriceXbox = 250.0,
                            Title = "Crusader Kings III"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Apex Legends is a free-to-play battle royale-hero shooter game developed by Respawn Entertainment and published by Electronic Arts. It was released for PlayStation 4, Windows, and Xbox One in February 2019, for Nintendo Switch in March 2021, and for PlayStation 5 and Xbox Series X/S in March 2022.",
                            DevStudio = "Respawn Entertainment",
                            GameCategoryId = 1,
                            ImageUrl = "C:\\Users\\czare\\source\\repos\\GameShop\\GameShop\\wwwroot\\images\\game\\Apex_legends_cover.jpg",
                            PricePS = 250.0,
                            PriceSteam = 200.0,
                            PriceXbox = 300.0,
                            Title = "Apex Legends"
                        },
                        new
                        {
                            Id = 8,
                            Description = "The game pits two teams, Terrorists and Counter-Terrorists, against each other in different objective-based game modes. The most common game modes involve the Terrorists planting a bomb while Counter-Terrorists attempt to stop them, or Counter-Terrorists attempting to rescue hostages that the Terrorists have captured.",
                            DevStudio = "Valve",
                            GameCategoryId = 1,
                            ImageUrl = "C:\\Users\\czare\\source\\repos\\GameShop\\GameShop\\wwwroot\\images\\game\\CSGOcoverMarch2020.jpg",
                            PricePS = 300.0,
                            PriceSteam = 200.0,
                            PriceXbox = 250.0,
                            Title = "Counter-Strike: Global Offensive"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Summaries. In this sequel to Doom (2016), Hell has taken Earth, so it's up to the Doom Slayer, the ultimate demon-killing machine created by a mystical force, to rip and tear the forces of Hell apart. However, Hell is not alone in this fight.",
                            DevStudio = "id Software",
                            GameCategoryId = 1,
                            ImageUrl = "C:\\Users\\czare\\source\\repos\\GameShop\\GameShop\\wwwroot\\images\\game\\Cover_Art_of_Doom_Eternal.png",
                            PricePS = 285.0,
                            PriceSteam = 199.0,
                            PriceXbox = 250.0,
                            Title = "DOOM Eternal"
                        });
                });

            modelBuilder.Entity("Models.Models.GameCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("GameCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "FPS"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Strategy"
                        },
                        new
                        {
                            Id = 3,
                            Category = "RPG"
                        });
                });

            modelBuilder.Entity("Models.Models.Game", b =>
                {
                    b.HasOne("Models.Models.GameCategory", "GameCategory")
                        .WithMany()
                        .HasForeignKey("GameCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
